export const trucks = [
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/bif-arenda-avtokrana-500-tonn.jpg",
    name: "Liebherr LTM 1500-8.1",
    weightLimit: 500,
    stickLength: 84,
    url: "https://bifgroup.ru/500-tonn/liebherr-ltm-1500-81",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/300tn_groovegmk6300l-1.jpg",
    name: "GMK 6300L-1",
    weightLimit: 300,
    stickLength: 80,
    url: "https://bifgroup.ru/300-tonn/grove-gmk-6300l-1",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda_avtokrana_bif_200_tonn.jpg",
    name: "Liebherr LTM 1200-5.1",
    weightLimit: 200,
    stickLength: 72,
    url: "https://bifgroup.ru/200-tonn/liebherr-ltm-1200-51",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/avtokran_220_tonn_1.jpg",
    name: "Автокран Grove GMK6220L",
    weightLimit: 220,
    stickLength: 72,
    url: "https://bifgroup.ru/220-tonn/grove-gmk6220l",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/ltm1250_b1.jpg",
    name: "Liebherr LTM 1250-6.1",
    weightLimit: 250,
    stickLength: 72,
    url: "https://bifgroup.ru/250-tonn/liebherr_ltm_1250",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda_avtokrana_bif_160_tonn.jpg",
    name: "Liebherr LTM 1160-5.1",
    weightLimit: 160,
    stickLength: 62,
    url: "https://bifgroup.ru/160-tonn/liebherr-ltm-1160-51",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/avtokran_100_tonn_grove_gmk4100l_1_0_0.jpg",
    name: "Автокран Grove GMK4100L",
    weightLimit: 100,
    stickLength: 60,
    url: "https://bifgroup.ru/100-tonn/grove-gmk4100l",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda_avtokrana_bif_130_tonn.jpg",
    name: "Liebherr LTM 1130-5.1",
    weightLimit: 130,
    stickLength: 60,
    url: "https://bifgroup.ru/130-tonn/liebherr-ltm-1130-51",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/bif-arenda-avtokrana-220-tonn.jpg",
    name: "Liebherr LTM 1220-5.2",
    weightLimit: 220,
    stickLength: 60,
    url: "https://bifgroup.ru/220-tonn/liebherr-ltm-1220-52",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda_avtokrana_bif_350_terex_tonn.jpg",
    name: "Terex-Demag AC 350",
    weightLimit: 350,
    stickLength: 56,
    url: "https://bifgroup.ru/350-tonn/terex-demag-ac-350",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda_avtokrana_bif_100_tonn.jpg",
    name: "Liebherr LTM 1100-5.1",
    weightLimit: 100,
    stickLength: 52,
    url: "https://bifgroup.ru/100-tonn/liebherr-ltm-1100-51",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/4276_6886595877158.jpg",
    name: "Grove GMK 4080-1",
    weightLimit: 80,
    stickLength: 51,
    url: "https://bifgroup.ru/80-tonn/grove-gmk-4080-1",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/80et_grovegmk4080.jpg",
    name: "Grove GMK 4080",
    weightLimit: 80,
    stickLength: 51,
    url: "https://bifgroup.ru/80-tonn/grove-gmk-4080",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/7657.jpg",
    name: "Автокран Liebherr LTM 1070-4.1",
    weightLimit: 70,
    stickLength: 50,
    url: "https://bifgroup.ru/70-tonn/liebherr-ltm-1070-42",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/bif_arenda_avtokrana_90tonn_liebherr_1090.jpg",
    name: "Liebherr LTM 1090-4.1",
    weightLimit: 90,
    stickLength: 50,
    url: "https://bifgroup.ru/90-tonn/liebherr-ltm-1090-41",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/avtokran_xcmg_xct70_s.png",
    name: "Автокран XCMG XCT70 S",
    weightLimit: 70,
    stickLength: 44.5,
    url: "https://bifgroup.ru/70-tonn/xcmg-xct70-s",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/1060_1_0.jpg",
    name: "Автокран Liebherr LTM 1060-2",
    weightLimit: 60,
    stickLength: 42,
    url: "https://bifgroup.ru/60-tonn/liebherr-ltm-1060-31",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/xcmg_1_1.jpg",
    name: "Автокран XCMG",
    weightLimit: 40,
    stickLength: 40,
    url: "https://bifgroup.ru/40-tonn/xcmg",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda-avtokrana-50_1.jpg",
    name: "Автокран Liebherr LTM 1050-3.1",
    weightLimit: 50,
    stickLength: 38,
    url: "https://bifgroup.ru/50-tonn/liebherr-ltm-1050-31",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda-avtokrana-40-tonn_0_0.jpg",
    name: "Автокран Terex AC 40/2L",
    weightLimit: 40,
    stickLength: 37.5,
    url: "https://bifgroup.ru/40-tonn/terex-ac-402l",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/avtokran_45_tonn_liebherr_1045-31_1.jpg",
    name: "Автокран LIEBHERR LTM 1045-3.1",
    weightLimit: 45,
    stickLength: 34,
    url: "https://bifgroup.ru/45-tonn/liebherr-ltm-1045-31",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda-krana-vezdehoda-25-tonn_1_0.jpg",
    name: "Галичанин 25 т /31 м (КС-55713-5В-4) - вездеход",
    weightLimit: 25,
    stickLength: 31,
    url: "https://bifgroup.ru/25-tonn/galichanin-25t-31m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda-avtokrana-40_1.jpg",
    name: "Terex-Demag AC-40 City",
    weightLimit: 40,
    stickLength: 31,
    url: "https://bifgroup.ru/40-tonn/terex-demag-ac-40-city",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/galichanin_32tonns_gusek_1.jpg",
    name: "Галичанин 32 т / 30,2 м + 9 м (КС-55729-1В)",
    weightLimit: 32,
    stickLength: 30.2,
    url: "https://bifgroup.ru/32-tonny/galichanin-302-m-9m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/32tn_galichanin.jpg",
    name: "Галичанин 32 т / 30,2 м (Галичанин КС-55729-5В)",
    weightLimit: 32,
    stickLength: 30.2,
    url: "https://bifgroup.ru/32-tonny/galichanin-ks-55729-5v",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/galichanin_32tonns_1.jpg",
    name: "Галичанин 32 т / 30,2 м (Галичанин КС-55729-1В)",
    weightLimit: 32,
    stickLength: 30.2,
    url: "https://bifgroup.ru/32-tonny/galichanin-302-m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/kc55713-5_2019_2.jpg",
    name: "Галичанин 25 т. /28,0 м (KC-55713-5В ) - вездеход",
    weightLimit: 25,
    stickLength: 28,
    url: "https://bifgroup.ru/25-tonn/galichanin-25t-28m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/25_28_1_0.jpg",
    name: "Галичанин 25 т / 28 м (Галичанин КС-55713-1В)",
    weightLimit: 25,
    stickLength: 28,
    url: "https://bifgroup.ru/25-tonn/galichanin-kamaz-28-m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/kilinci_25tonn_28metrov_gusek_1.jpg",
    name: "Клинцы 25 т / 28 м + 9 м (Клинцы КС-55713-1К2)",
    weightLimit: 25,
    stickLength: 28,
    url: "https://bifgroup.ru/25-tonn/klincy-kamaz-28-m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/galichanin-kamaz2179.jpg",
    name: "Галичанин-Камаз 25 т / 21,7 м + 9 м (КС-55713)",
    weightLimit: 25,
    stickLength: 21.7,
    url: "https://bifgroup.ru/25-tonn/galichanin-kamaz-217-m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/21_galichanin_maz_0.jpg",
    name: "Галичанин-Маз 25 т / 21,7 + 9 м (Галичанин КС-55713-6)",
    weightLimit: 25,
    stickLength: 21.7,
    url: "https://bifgroup.ru/25-tonn/galichanin-maz-217-m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/bif-arenda-avtokrana-25-tonn-1.jpg",
    name: "Галичанин-Камаз 25 т / 21,7 м (Галичанин КС-55713-1)",
    weightLimit: 25,
    stickLength: 21.7,
    url: "https://bifgroup.ru/25-tonn/galichanin-kamaz-25-t-217-m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/bif-arenda-avtokrana-25-tonn-vezdehod.jpg",
    name: "Клинцы (вездеход) 25 т / 21,7 м (Клинцы КС-55713-5К)",
    weightLimit: 25,
    stickLength: 21.7,
    url: "https://bifgroup.ru/25-tonn/klincy-kamaz-vezdehod-217-m",
  },
  {
    src: "https://bifgroup.ru/sites/default/files/styles/gallery/public/arenda-avtokrana-klincy-25-tonn.jpg",
    name: "Клинцы 25 т / 21,7 м (Клинцы КС-55713-1К-1)",
    weightLimit: 25,
    stickLength: 21.7,
    url: "https://bifgroup.ru/25-tonn/klincy-kamaz-217-m",
  },
];
